format_version: 4
common:
  apply_job: &apply_job
    resources:
      - docker
    artifacts:
      - build:
          source: tf-out.json
    tasks:
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks create_secrets
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_plan create
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_apply

pipelines:
  "prm-deductions-infra":
    group: deductions
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
    stages:
      - deploy_dev:
          clean_workspace: true
          environment_variables:
            NHS_ENVIRONMENT: dev
          jobs:
            apply: *apply_job

      - deploy_test:
          clean_workspace: true
          environment_variables:
            NHS_ENVIRONMENT: test
          jobs:
            apply: *apply_job
