- name: Install stunnel
  apt: name=stunnel4

- name: Generate an OpenSSL private key
  openssl_privatekey:
    path: /etc/stunnel/key.pem
    size: 2048

- name: Generate an OpenSSL Certificate Signing Request
  openssl_csr:
    path: /etc/stunnel/cert.pem.csr
    privatekey_path: /etc/stunnel/key.pem
    common_name: "{{ env }} deductions"

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: /etc/stunnel/cert.pem
    privatekey_path: /etc/stunnel/key.pem
    csr_path: /etc/stunnel/cert.pem.csr
    provider: selfsigned
    subject:
      commonName: "{{ env }} deductions"

- name: Create stunnel certificates bundle
  shell:
    cmd: cat key.pem cert.pem >> /etc/stunnel/{{ env }}-stunnel.pem
    chdir: /etc/stunnel/

- name: Configure stunnel server
  template:
    src: stunnel.conf.j2
    dest: /etc/stunnel/stunnel.conf
  notify: restart stunnel4

- name: Configure stunnel daemon
  template:
    src: stunnel4.j2
    dest: /etc/default/stunnel4
  notify: restart stunnel4

- name: Setup stunnel systemd service
  systemd:
    enabled: true
    state: started
    daemon_reload: yes
    name: stunnel4
